<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RDLC.Infrastructure\RDLC.Infrastructure.csproj" />
    <ProjectReference Include="..\RDLC.Services\RDLC.Services.csproj" />
    <ProjectReference Include="..\RDLC.Shared\RDLC.Shared.csproj" />
  </ItemGroup>

</Project>
